VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "EventClassModule"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Public WithEvents appWordS As Word.Application
'
'Private Sub appWordS_DocumentOpen(ByVal Doc As Document)
'    Call Switch.template_switcher
'End Sub
'
'Private Sub appWordS_NewDocument(ByVal Doc As Document)
'    Call Switch.template_switcher
'End Sub

'Private Sub appWordS_WindowActivate(ByVal Doc As Document, ByVal Wn As Window)
'    Call Switch.template_switcher
'End Sub
